language: ruby
sudo: false
services:
  - postgresql

matrix:
  include:
    rvm:
      - 2.4.10
      - 2.5.8
      - 2.6.6
      - 2.7.1

before_script:
  - psql -c 'create database granite_ci_test;' -U postgres
  - cp spec/support/database.yml.travis spec/support/database.yml
script:
  - bundle exec rspec
  - bundle exec rubocop
